### PR TITLE
Final submission

### PR DESCRIPTION
**Pull request by SeungKiLeeCS**
**Jenn Le**           45920619  
**Seung Ki Lee**  35460312  

Professor Dave,

The functionality of our application is mostly implemented. The app can register and authenticate a user, create and join playlists, search and add youtube videos in app, automatically plays the next video once current video ends,  keeps track of which users are in the room, etc. It's not quite production ready, but I believe it is submission ready.

Here is the instruction on how to test the application. If there are any problems or questions, please let us know!

### Backend

The API is set up as an elixir umbrella app with different functions separated into different apps. Ecto and database schema definitions are organized into the appropriate apps rather than isolated as a database app.

To set up the Postgres DB:
`docker run --name endlist-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=endlist_dev -d postgres`

To start your Phoenix server:
`mix deps.get`  
`mix ecto.create && mix ecto.migrate`  

please run `source config/app.env` before you run the server. We understand having the api_key up on github is a terrible thing, but for the submission we are focusing on getting things to work.

`mix phx.server`  

### Frontend

`npm install`  

Then, To start the electron app:
`npm run dev`

### Code
[Master Branch](https://github.com/Thakugan/endlist/)

### CODE REVIEW

**Comment by pragdave** [comment]
Folks: this PR only contains 1 file....

**Comment by SeungKiLeeCS** [comment]
> Folks: this PR only contains 1 file....

Professor,

The code is on another repo linked at the bottom; I am very sorry about the confusion.

**Comment by pragdave** [comment]
My mistake...

**Comment by pragdave** [comment]
Wow! What a lot of work.

I ran out of time trying to get it to fully work (it needed a YouTube api key do search for videos) but this didn't impact the grade.

Although I said I wasn't going to look at thew JavaScript, I lied :) I was interested to see how you did the websockets integration, and I liked what I saw.

Back on the Elixir side, I liked the way you split the two database components. Interestingly, though, there's a circular dependency between them. This means you can compile them together as an umbrella app, but not separately. This isn't something I've bumped into before, because I typically don't have inter-component dependencies like that.

Your Elixir code was a delight to read, and is clearly open to change it needed. It is well structured and laid out. I really have nothing negative to say about it.

Well done, both of you!

VetoTheBeto2018?  :)

**Pull request closed without merging**
