### PR TITLE
Final Submission

### PR DESCRIPTION
**Pull request by lchansen**
Lucas Hansen
4666-8000

[Click here ](https://github.com/lchansen/skydock_secrets/invitations) to accept the invite to my skydock_secrets repo. Make sure to use the same credentials @pragdave when you checkout lchansen/05-coders-choice (master) in order to also clone this private repo as a submodule.

[README.md](https://github.com/lchansen/05-coders-choice/blob/master/README.md) contains all necessary running instructions

Note: Requires use of US phone number if you use the "logs <container>", which sends a MMS, not just an SMS

### CODE REVIEW

**Comment by pragdave** [comment]
Luke:

I _think_ I've plumbed this together correctly, but when I text "get containers", I get

~~~
2∙00∙26≻ sudo mix phx.server
Password:
[info] Running SdWeb.Endpoint with Cowboy using http://0.0.0.0:80
12:00:42 - info: compiled 6 files into 2 files, copied 3 in 1.5 sec
[info] GET /
[debug] Processing with SdWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 85ms
[info] POST /sms
[debug] Processing with SdWeb.PageController.handle_sms/2
  Parameters: %{"AccountSid" => "ACc619824dcde9ee20511393d004734a06", "ApiVersion" => "2010-04-01", "Body" => "Qfggg", "From" => "+12142336543", "FromCity" => "EULESS", "FromCountry" => "US", "FromState" => "TX", "FromZip" => "75247", "MessageSid" => "SM723e10da1d6fec6adfca0902fdc7da97", "NumMedia" => "0", "NumSegments" => "1", "SmsMessageSid" => "SM723e10da1d6fec6adfca0902fdc7da97", "SmsSid" => "SM723e10da1d6fec6adfca0902fdc7da97", "SmsStatus" => "received", "To" => "+13093798162", "ToCity" => "STANFORD", "ToCountry" => "US", "ToState" => "IL", "ToZip" => "61704"}
  Pipelines: [:browser]
[info] Sent 200 in 43ms
{:error,
 %{
   "code" => 20404,
   "message" => "The requested resource /2010-04-01/Messages.json was not found",
   "more_info" => "https://www.twilio.com/docs/errors/20404",
   "status" => 404
 }, 404}
[info] POST /sms
[debug] Processing with SdWeb.PageController.handle_sms/2
  Parameters: %{"AccountSid" => "ACc619824dcde9ee20511393d004734a06", "ApiVersion" => "2010-04-01", "Body" => "get containers", "From" => "+12142336543", "FromCity" => "EULESS", "FromCountry" => "US", "FromState" => "TX", "FromZip" => "75247", "MessageSid" => "SMeab2e14c9f07b1397f8d57d740506e3a", "NumMedia" => "0", "NumSegments" => "1", "SmsMessageSid" => "SMeab2e14c9f07b1397f8d57d740506e3a", "SmsSid" => "SMeab2e14c9f07b1397f8d57d740506e3a", "SmsStatus" => "received", "To" => "+13093798162", "ToCity" => "STANFORD", "ToCountry" => "US", "ToState" => "IL", "ToZip" => "61704"}
  Pipelines: [:browser]
[info] Sent 200 in 1ms
{:error,
 %{
   "code" => 20404,
   "message" => "The requested resource /2010-04-01/Messages.json was not found",
   "more_info" => "https://www.twilio.com/docs/errors/20404",
   "status" => 404
 }, 404}
~~~

Any ideas?

**Comment by pragdave** [comment]
Lucas:

This is a fantastic piece of work. I love the integrations you've done, and the way you've structured this.

I also really appreciate the work you've done to make this easy for me to run. (And I learned a useful trick with the env-file submodule idea).

No comments on the code at all. Very well done!

**Comment by lchansen** [comment]
Sorry I’m just now seeing this. Are you still having issues with “get containers”?
I can try to resolve when I’m home from the store

**Comment by pragdave** [comment]
Yes, but it hasn't prevented me from grading it. (you got 105%...)

**Pull request closed without merging**
