### PR TITLE
Final Submission

### PR DESCRIPTION
**Pull request by zchbndcc9**
My final PR is in my private repo [here](https://github.com/zchbndcc9/Spotify-Matcher/pull/19) for your viewing and reviewing pleasure.

I had a lot of fun with this application! I think that it is good in its current state, but there are a couple of things that I think I can improve. The primary being that for some reason, the `spotify_ex` application that I am using occasionally fails to add tracks to the playlist that is created. That being said, it may take longer to fulfill the request from the webpage, so just be patient. The request will go through and you will be able to view your new playlist via Spotify

I would really appreciate some feedback too since I plan on iterating on the app and I'll be continuing development. It's been a pleasure!

Zach Banducci
44671228

### CODE REVIEW

**Comment by pragdave** [comment]
Zach:

I currently can't compile the project. I'm running in your dev branch, and when I try to compile playlist_builder I get

~~~
~/t/S/a/playlist_builder|dev ⚡
18∙16∙45≻ mix compile
Compiling 3 files (.ex)

== Compilation error in file lib/playlist_builder.ex ==
** (CompileError)  deadlocked waiting on struct Plug.Conn


== Compilation error in file lib/playlist.ex ==
** (CompileError)  deadlocked waiting on struct Plug.Conn
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3

Compilation failed because of a deadlock between files.
The following files depended on the following modules:

  lib/playlist_builder.ex => Plug.Conn
          lib/playlist.ex => Plug.Conn

Ensure there are no compile-time dependencies between those files and that the modules they reference exist and are correctly named
~~~

Also, what's the format of spotify_secret.exs?

**Comment by zchbndcc9** [comment]
Whoops! Looks like I forgot to include the API keys in the `server/config` folder. I didn't want to put my API keys on Github for security reasons. I just sent you the file via email. Just insert the keys in the config file of the server app and you should be good to go

**Comment by zchbndcc9** [comment]
As for the compilation issue, try compiling from the root directory

**Comment by zchbndcc9** [comment]
Also I am thinking about utilizing channels in order to reduce the need for HTTP requests, but in order to do that I'll need to find a way to handle the Spotify JW tokens on the server side for a given user

**Comment by pragdave** [comment]
Zach:

I don't see that email here...

**Comment by zchbndcc9** [comment]
I believe I sent it davidthomas@mail.smu.edu if that is the correct email. If it is not there, what other means would I be able to get the keys to you?

**Comment by zchbndcc9** [comment]
Here is the format of my config file for times sake. I apologize for the inconvenience

```elixir
use Mix.Config

config :spotify_ex, client_id: "0c673ec5402d4ceca3ae9b4de22ccd73",
                    secret_key: "625331c012434b9985bec3e22fe7f9ab"

```

**Comment by pragdave** [comment]
I'm seeing

MatchError at GET /no match of right hand side value: {:ok, %{"error" =>
%{"message" => "Only valid bearer authentication supported", "status" =>
400}}}
lib/server_web/controllers/page_controller.ex <http://localhost:4000/>

1defmodule ServerWeb.PageController do2  use ServerWeb, :controller34
def index(conn, _params) do5    {:ok, %Spotify.Profile{ id: id }} =
Spotify.Profile.me(conn)6    ArtistManager.restart_store(id)7
render(conn, "app.html")8  end9end

**Comment by zchbndcc9** [comment]
Go ahead and put http://localhost:4000/authorize into the url and then navigate back to http://localhost:4000 once you have been authorized by Spotify

**Comment by pragdave** [comment]
Now I get logged in OK, but I see

Please pick at least 5 artists
Playlist Info
Playlist Title
Number of Songs
10
30
50

There's no place to enter artists. In the JS console, I see:

react-dom.development.js:510 Warning: Invalid DOM property `class`. Did you
mean `className`?
    in div (created by Home)
    in div (created by Home)
    in div (created by Home)
    in Home (created by ReactApp)
    in ReactApp

**Comment by zchbndcc9** [comment]
Hmmm although that is *an* issue, I don't think that is it. I am able to see the artist cards on my machine. It should look something like this: 
screen shot 2018-12-13 at 1 04 23 pm

My application populates the cards with your top artists so if you aren't an avid Spotify user, they may be blank

**Comment by zchbndcc9** [comment]
In the future, I plan on allowing users to enter in artists as well

**Comment by pragdave** [comment]
ah, that's it then. I haven't used it for years... :(

**Comment by zchbndcc9** [comment]
Aw bummer :( Well that's a shame. Sorry about that. Thanks again for a great semester!!!

**Pull request closed without merging**
