### PR TITLE
Proposal

### PR DESCRIPTION
**Pull request by CaseyH19**
Casey Hittinger
43199706
Sanity Check 1

I am having trouble figuring out how to send a map of the state of the board to an elixir file. I was wondering if you could give me any pointers on the organization of everything. I tried to follow past examples like the chatty one but we were not really saving state as a map or anything.

### CODE REVIEW

**Comment by pragdave** [comment]
In the Javascript you can just a JS object, which will be received as an Elixir map with string keys.

I'd be happy to connect over zoom on  Monday, or before or after class Tuesday.

I'd recommend getting most of the requirements done by the next checkin: right now I feel you're a little behind.

**Comment by CaseyH19** [comment]
Can we meet before class on tuesday/tomorrow? Maybe 10:45? You can tell me the location.

**Comment by pragdave** [comment]
Do you have a class immediately before? If not, how about 11:45? We could
meet at The Market in Hughes-Triggs.

**Comment by CaseyH19** [comment]
No i do not have a class. My bad i meant 11:45. 
Sounds like a plan! Ill see you there.

**Comment by pragdave** [comment]
If I'm at all late, it'll be because I had to park in Waco. Be patient.

**Pull request closed without merging**
